dist: bionic
language: scala
scala: 2.13.1
branches:
  except:
    - dev-prerelease
env:
  matrix:
    - PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  global:
    # GH_TOKEN=abcde: authorized to push
    secure: eqD1V2aWz4ggaSMT4oZK5VcOd8Wu7zYfuPPX91jW3iupRuFMVPTc3lozhzMbS0c6HBwhu1RvQGYqJxtQ41BnR/Wg9F92+pXfxd0X5OngI9GR2CJ3JM3sEqUZfxIhUGUW1U1GOzm32Z9W8gFie9gsTfl3KEkzT30dUENFjOkNJIf17DqSsrR+Mg3rj1ILR7d6NgGsy0reV8y3k17ajZmnNrbMbAx1PQDyGU8yjfsymjZoZY5A0lhG1uYhEKDFuLH8ep1VPbNqA3n4M8pbrtgDnZZRfsKohRl9nOP4lpZUam2yOKZ78YNMe7X5tHytdYC5HorsibJrcS00Vp6R4j30PXeQeNq6G9livmevVfifSJ1I4PKHc33RXUOqNoWZ5D4ft07MfZZsAUVrvmpR1oj2x9iXBr6k3yNUH2Bu+rpmG6Ewk0aFAm04uhFlReSWRLuNdi8Mfp5zdDrzPKTWG3pOYyL7j6MLwS6YZ0WO1I3BiR6ii6kidR4Bbpu/11ik5/Hbe9+vZ9pESg5RDQf4gQjTWc8L0WH/y767Fo4wbwITGuGkNLdAlGMbb+h2wPK/W5EuCNpnzLCDNpn7xz37c1uTiK9JXI18qx8/VgBGY12qk7avgQvbkI5zXPqo1fdZgpK6fXdKxJdF47ZhmZbuQCjp8EpCPNlVwhzVHQKfG+S3egU=

    # VERCORS_RSYNC_PASSWORD
    secure: "BmCRtuUyZexNVbuu9QjRZ1P+4nAyDK1vLbFbhsxOT4HuOJx7arsKjYMGtpn+mGiUzw0Qid11DZ5VoE91ip7KxfNIPOViRLVs9EC+r4NcsC0fgik9/3iElZhg0AoHP9Gzblt8nYpzdRXhK6rFxn0FzHK305+tJw1soMzmIrRT8xBeAW4cStABPaOvtUENY1BYYWk5WIXD98ZM+bdMaR/lDdFM32XF8A+w3EbXiD8W3gxUvy4PbZKXM+XgjPg4mJnuY1Xshixbl+OjqNPGDw2J6sk2NyrArQ8mHV6xTWv3SLQOCGJWO80OYaBogzwZlyrItpT2nNVolFNMf7QURiQQRa3iO6hbgXLH1mYC4zvOmTAw1IOKwUwKrp2ALU50ecmi1JXS/xz8xoull8KnM4FSr5dv403j+5LOcL3XyhMGg4kYCiPtueEcFvgRVMV1WSc2uGM8YpFLTsDwYBGPdW1xu9QfegR1Je/N0TNM2DxWQQ5mHpfNISyU4mrdjh9PhEMn3bUbn52PP5F6NGzdttnddU4oeVz23bt0AeyyUuax1vOa9HayoN1qHXBu5ZVTm0776UoHhlWfzZ7U8gjJMuOUhl3t3suQgN2Fi2rtpeF3NCe8enXcMckrAKpygie22ZtBLY/vHWx1/60HXq7UWwMVGP6UIn14nVlY+6nIhwWwUyA="
addons:
  apt:
    packages:
      - tree # For debug printing sync folder
cache:
  directories:
    - "~/.cache/coursier"
    - "~/.ivy2/cache"
    - "~/.sbt"
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
matrix:
  include:
    - stage: Build
      script: .travis/buildArchives.sh
      addons:
        apt:
          packages:
            - fakeroot
            - tree
      after_failure: .travis/clearBuildData.sh
    - stage: Tests
      script:
        - SPLIT=0/5 ./.travis/build.sh
      after_failure: .travis/clearBuildData.sh
    - script:
        - SPLIT=1/5 ./.travis/build.sh
    - script:
        - SPLIT=2/5 ./.travis/build.sh
      after_failure: .travis/clearBuildData.sh
    - script:
        - SPLIT=3/5 ./.travis/build.sh
      after_failure: .travis/clearBuildData.sh
    - script:
        - SPLIT=4/5 ./.travis/build.sh
      after_failure: .travis/clearBuildData.sh
    - stage: Analysis
      addons:
        sonarcloud:
          organization: utwente-fmt
          token:
            secure: rN1xKIRlcnyPz0wtlmzF5AW04f57sPVmhDe3TjXWho84YWE5eu6avdV36NeS6PHrocKpcLY3PLLqtNs6FPMmlN2fBvLQs8Z0iEkhfrJv3moq9GuE8la6D4845iR7Kw+gtqbDS7cVDh9zZ33zVvgK+faLz6yy+NopXcyO4cxYPUhKypyvCGnPNxCLUuW8bq+0pV1xbuqhd+r18Zd+UQCiX5RE/1Zio5LuXLkPfO+fy1D7/OKwzA5sjWS2oNsIR9w5jRA7IVK4gbfm/wgkwkRhMDlezXpsSWTXQq0Ib8HgER3GkFjCF0rqtsEYKSvDuo80paVrbZEnT/lEu7+5UV5BbhN/pTaKW4or8b1dFbUOJTlxJXVXhO8VgdHO88OrKWlvq4KJjq48ZPchHx30lKHAeCVOW9m2lfFXM9I/8vnFQgQ7HEC+TvYwyWLqDv+ZNAJ9qQSYYJby5ZWaTRr306eERj1xFPrljbw/g9SpKMMM66C8PfbCgn06X/PeaycqrcgZLd1mYyKNB7+vGt9x4IN3wJAdV+H2Y0EYZuIF+GEX1D6+zYjFF7bZhl/xHW/oQC8PxxmE9D7QBU1SHhwOybCeujvbYk/7XrHVK2vic2KbScKyeTthJeqVUE616xImTyhJcVJti1AMchLdUmppsfTVRHkOG6HniLmIJIQpV+Ajz2k=
        apt:
          packages:
            - checkstyle
            - tree
      script:
        - .travis/analyse.sh
      after_failure: .travis/clearBuildData.sh
    - stage: Deploy
      if: branch = dev AND type = push
      addons:
        apt:
          packages:
            - fakeroot
            - tree
      script:
        - ./.travis/downloadBuildData.sh
      before_deploy:
        - git config --local user.name "Vercors Team"
        - git config --local user.email "vercors@lists.utwente.nl"
        - git tag --force dev-prerelease
        - git remote set-url origin https://${GH_TOKEN}@github.com/utwente-fmt/vercors.git
        - git push --force --tags
      deploy:
        skip_cleanup: true
        on:
          branch: dev
        provider: releases
        api_key:
          secure: b4iofzSKeLe72qAJRwRkcPIFYKlnwOdT8Jk0o6Z2ml3QWghwg0XjinNkBvukT9mAfwF4fU/e0cqonXwLMti8azZ0Us59SWi8+GdYKnO9U5hWEEHY/3v42jspHS29khABkeJ7gULNIXpEWOGUDg/Muc/PbmUQqMctyRYPMDSmFsvF27ESvfOqPM21cS7wByovtvvkFR7FS6TNne/noiroC++zOkFGISf+y8UrVggCRyHsqi7a5Xep5wfVFSaZP/PYov2ewkLHl0eRmz0dJGtQNqVPfMx5hzd/xM73X+FwNzMHEJv4n1JeRKY5t3UizYL0hlJX1K5gMRmvmMEnr6hs8EpQftTw+ciLEVKJuVvec3cruSQueZmXrsLMmquaXyUdNoVnC7H+MoVT+u8IN40EbvWhUvolE8DvtxfMC53HbMEWStM5mHVncTW5f8ralC49hwjX/sWjCBDfcTbXHtHMQ649o20+fky+kKvHXa9/YrZDPAk6byY7u39kkM5GxJ940qO2nxUCr6hnpL8WOR4MhhwHAhOpERtbnVc07+vMH9bUbnkOuAtJbXTpjFNYQ1ep41ulqBihwSHX53gT/tfdXVcRxpY+kJRlUSAgkk1tn5IZPvZHuT6NG2A1m7NJ3rOC33759ufdlwW9/nhgdaAnW5sF9RxfCk5hNxK7kPfhyeI=
        prerelease: true
        name: Vercors Dev Build
        overwrite: true
        file_glob: true
        file:
          - "$TRAVIS_BUILD_DIR/sync/$TRAVIS_BUILD_NUMBER/*.deb"
          - "$TRAVIS_BUILD_DIR/sync/$TRAVIS_BUILD_NUMBER/*.txz"
