dist: bionic
language: scala
scala: 2.13.1
env:
- PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
addons:
  sonarcloud:
    organization: utwente-fmt
    token:
      secure: rN1xKIRlcnyPz0wtlmzF5AW04f57sPVmhDe3TjXWho84YWE5eu6avdV36NeS6PHrocKpcLY3PLLqtNs6FPMmlN2fBvLQs8Z0iEkhfrJv3moq9GuE8la6D4845iR7Kw+gtqbDS7cVDh9zZ33zVvgK+faLz6yy+NopXcyO4cxYPUhKypyvCGnPNxCLUuW8bq+0pV1xbuqhd+r18Zd+UQCiX5RE/1Zio5LuXLkPfO+fy1D7/OKwzA5sjWS2oNsIR9w5jRA7IVK4gbfm/wgkwkRhMDlezXpsSWTXQq0Ib8HgER3GkFjCF0rqtsEYKSvDuo80paVrbZEnT/lEu7+5UV5BbhN/pTaKW4or8b1dFbUOJTlxJXVXhO8VgdHO88OrKWlvq4KJjq48ZPchHx30lKHAeCVOW9m2lfFXM9I/8vnFQgQ7HEC+TvYwyWLqDv+ZNAJ9qQSYYJby5ZWaTRr306eERj1xFPrljbw/g9SpKMMM66C8PfbCgn06X/PeaycqrcgZLd1mYyKNB7+vGt9x4IN3wJAdV+H2Y0EYZuIF+GEX1D6+zYjFF7bZhl/xHW/oQC8PxxmE9D7QBU1SHhwOybCeujvbYk/7XrHVK2vic2KbScKyeTthJeqVUE616xImTyhJcVJti1AMchLdUmppsfTVRHkOG6HniLmIJIQpV+Ajz2k=
cache:
  directories:
  - "~/.cache/coursier"
  - "~/.ivy2/cache"
  - "~/.sbt"
before_cache:
- rm -fv $HOME/.ivy2/.sbt.ivy.lock
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
matrix:
  include:
#  - script:
#    - SPLIT=0/5 ./.travis/build.sh
#  - script:
#    - SPLIT=1/5 ./.travis/build.sh
#  - script:
#    - SPLIT=2/5 ./.travis/build.sh
#  - script:
#    - SPLIT=3/5 ./.travis/build.sh
#  - script:
#    - SPLIT=4/5 ./.travis/build.sh
#  - script:
#    - ./.travis/travis_fold.sh build "Build Vercors" "sbt compile"
#    - echo "TRAVIS_SECURE_ENV_VARS=${TRAVIS_SECURE_ENV_VARS}";
#    - 'if [ "${TRAVIS_SECURE_ENV_VARS}" == "false" ]; then echo; echo "The check is
#      running for a pull request for an external repo. At the moment Travis does not
#      support running Sonar for external repositories. The build will fail."; fi;'
#    - ./.travis/travis_fold.sh sonar "Sonar" "sonar-scanner"
  - addons:
      apt:
        packages:
          - fakeroot
    script:
    - ./.travis/travis_fold.sh build "Build Vercors" "sbt debian:packageBin universal:packageXzTarball"
    before_deploy:
    - git config --local user.name "Vercors Team"
    - git config --local user.email "vercors@lists.utwente.nl"
    - export COMMIT_TAG=v$(sbt version | tail -n1 | cut -b8-)-$(date +'%Y-%m-%d-%H%M%S')
    - git tag $COMMIT_TAG
    deploy:
      on:
        branch: ci-cd
      provider: releases
      api_key:
        secure: b4iofzSKeLe72qAJRwRkcPIFYKlnwOdT8Jk0o6Z2ml3QWghwg0XjinNkBvukT9mAfwF4fU/e0cqonXwLMti8azZ0Us59SWi8+GdYKnO9U5hWEEHY/3v42jspHS29khABkeJ7gULNIXpEWOGUDg/Muc/PbmUQqMctyRYPMDSmFsvF27ESvfOqPM21cS7wByovtvvkFR7FS6TNne/noiroC++zOkFGISf+y8UrVggCRyHsqi7a5Xep5wfVFSaZP/PYov2ewkLHl0eRmz0dJGtQNqVPfMx5hzd/xM73X+FwNzMHEJv4n1JeRKY5t3UizYL0hlJX1K5gMRmvmMEnr6hs8EpQftTw+ciLEVKJuVvec3cruSQueZmXrsLMmquaXyUdNoVnC7H+MoVT+u8IN40EbvWhUvolE8DvtxfMC53HbMEWStM5mHVncTW5f8ralC49hwjX/sWjCBDfcTbXHtHMQ649o20+fky+kKvHXa9/YrZDPAk6byY7u39kkM5GxJ940qO2nxUCr6hnpL8WOR4MhhwHAhOpERtbnVc07+vMH9bUbnkOuAtJbXTpjFNYQ1ep41ulqBihwSHX53gT/tfdXVcRxpY+kJRlUSAgkk1tn5IZPvZHuT6NG2A1m7NJ3rOC33759ufdlwW9/nhgdaAnW5sF9RxfCk5hNxK7kPfhyeI=
      prerelease: true
      file_glob: true
      file:
        - target/*.deb
        - target/universal/*.txz