language: scala

scala:
 - 2.11.7
 
env:
 - PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH

#cache:
#  directories:
#    - $HOME/.sbt

notifications:
  email:
    recipients:
      - s.c.c.blom@utwente.nl
    on_success: change
    on_failure: always


addons:
  apt:
    packages:
      - mono-complete
      - tcl

script:
 - ant jar
 - vct --test="",$TRAVIS_BUILD_DIR/examples/permissions

deploy:
  provider: releases
  api_key:
    secure: MFGqeFi8E9eLtcy+5wQ/+xgSKyg3QY2Jm0wRBk6GWyIh3WUdjhI0Fqe3rII/r+AyB2tC3tA8zNzNRar1wOYgVr8zLQwwsfq+K/PfeOPitkKiPmUICeZXEXpTgOhkg53vynN+ZXwV4UcEKR64Z7LMK0mWqpCf3jzv8S9fu0/zV/cwo86LNbHPTRJtVxst25YUVL9X9U3lV7Q+KvRgephjuIG2gz/Ce63uVxVGiTMFETzeL0FM8hdSQUCcRKIFysDxhOh+oofPLkGQOQsET4atNYsqmEXOMnZjU07muqXTrsybz/PhTW2Ioi3AdCR/tfNnoOhBiON6hWyR66db8DKNfiyLmFvyEFsOLm5nNhucU4wvRslRyMfayn+D4nRc/I0I4ozifl0WXfqBbtAqFtUUV1cuWZfIDH9OJF5YfB2mbUs9FYo5CpopjNnGV8rlkzzGm15EWQhMTeq1qpxl+E2NsY0UZ3DoxLRzLEvoykpN9VatiYkrpX6jG9g2u1GZ6E/fDw5NwouUI/tLeaFhvHydMx7GVewKRNWuLC0hct92tKWtjV9tLCVzOoHGuDmWZVRLH6Zn5XJvCfhBZvu7RcM9S5UdJbdW5PYf8qYgTqteIoXYKQUofOGUCsbsBncLuiRT9I1pXMYolAcd06KfTdmhk6QHYCAN1JP6Rgz//r3osSc=
  file: 'dist/vercors-$TRAVIS_TAG.zip'
  on:
    repo: utwente-fmt/vercors
    tags: true  
