dist: xenial

language: scala
scala:
- 2.11.7

jdk:
- openjdk11

env:
  - SPLIT=0/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=1/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=2/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=3/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=4/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=5/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=6/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=7/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=8/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=9/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=10/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=11/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=12/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=13/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=14/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=15/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=16/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=17/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=18/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH
  - SPLIT=19/20 PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH


addons:
  apt:
    packages:
      - tcl
      - texlive
      - texlive-latex-recommended
      - texlive-latex-extra
  sonarcloud:
    organization: utwente-fmt
    token:
      secure: "rN1xKIRlcnyPz0wtlmzF5AW04f57sPVmhDe3TjXWho84YWE5eu6avdV36NeS6PHrocKpcLY3PLLqtNs6FPMmlN2fBvLQs8Z0iEkhfrJv3moq9GuE8la6D4845iR7Kw+gtqbDS7cVDh9zZ33zVvgK+faLz6yy+NopXcyO4cxYPUhKypyvCGnPNxCLUuW8bq+0pV1xbuqhd+r18Zd+UQCiX5RE/1Zio5LuXLkPfO+fy1D7/OKwzA5sjWS2oNsIR9w5jRA7IVK4gbfm/wgkwkRhMDlezXpsSWTXQq0Ib8HgER3GkFjCF0rqtsEYKSvDuo80paVrbZEnT/lEu7+5UV5BbhN/pTaKW4or8b1dFbUOJTlxJXVXhO8VgdHO88OrKWlvq4KJjq48ZPchHx30lKHAeCVOW9m2lfFXM9I/8vnFQgQ7HEC+TvYwyWLqDv+ZNAJ9qQSYYJby5ZWaTRr306eERj1xFPrljbw/g9SpKMMM66C8PfbCgn06X/PeaycqrcgZLd1mYyKNB7+vGt9x4IN3wJAdV+H2Y0EYZuIF+GEX1D6+zYjFF7bZhl/xHW/oQC8PxxmE9D7QBU1SHhwOybCeujvbYk/7XrHVK2vic2KbScKyeTthJeqVUE616xImTyhJcVJti1AMchLdUmppsfTVRHkOG6HniLmIJIQpV+Ajz2k="

cache:
  directories:
   - $HOME/.ivy2
   - $HOME/Library/Caches/Homebrew
   - /usr/local/Homebrew

script:
# Compile the tool
- ./travis_fold.sh build "Building VerCors" "sh travis_build.sh"
# Test one example that shows all error messages
- ./travis_fold.sh fibonacci "Checking manual example" "vct --silicon $TRAVIS_BUILD_DIR/examples/manual/fibonacci.pvl"
# Test the remaining examples while hiding messages
- ./travis_fold.sh test "Executing tests" "vct --tool=silicon --exclude-suite=slow,medium,problem-fail,skip-travis --test=$TRAVIS_BUILD_DIR/examples --progress"
# Run the Sonar scanner
- ./travis_fold.sh sonar "Sonar" "sonar-scanner"

#deploy:
#  provider: releases
#  api_key:
#    secure: MFGqeFi8E9eLtcy+5wQ/+xgSKyg3QY2Jm0wRBk6GWyIh3WUdjhI0Fqe3rII/r+AyB2tC3tA8zNzNRar1wOYgVr8zLQwwsfq+K/PfeOPitkKiPmUICeZXEXpTgOhkg53vynN+ZXwV4UcEKR64Z7LMK0mWqpCf3jzv8S9fu0/zV/cwo86LNbHPTRJtVxst25YUVL9X9U3lV7Q+KvRgephjuIG2gz/Ce63uVxVGiTMFETzeL0FM8hdSQUCcRKIFysDxhOh+oofPLkGQOQsET4atNYsqmEXOMnZjU07muqXTrsybz/PhTW2Ioi3AdCR/tfNnoOhBiON6hWyR66db8DKNfiyLmFvyEFsOLm5nNhucU4wvRslRyMfayn+D4nRc/I0I4ozifl0WXfqBbtAqFtUUV1cuWZfIDH9OJF5YfB2mbUs9FYo5CpopjNnGV8rlkzzGm15EWQhMTeq1qpxl+E2NsY0UZ3DoxLRzLEvoykpN9VatiYkrpX6jG9g2u1GZ6E/fDw5NwouUI/tLeaFhvHydMx7GVewKRNWuLC0hct92tKWtjV9tLCVzOoHGuDmWZVRLH6Zn5XJvCfhBZvu7RcM9S5UdJbdW5PYf8qYgTqteIoXYKQUofOGUCsbsBncLuiRT9I1pXMYolAcd06KfTdmhk6QHYCAN1JP6Rgz//r3osSc=
#  file: 'dist/vercors-$TRAVIS_TAG.zip'
#  on:
#    repo: utwente-fmt/vercors
#    tags: true

deploy:
  provider: releases
  api_key:
    secure: MFGqeFi8E9eLtcy+5wQ/+xgSKyg3QY2Jm0wRBk6GWyIh3WUdjhI0Fqe3rII/r+AyB2tC3tA8zNzNRar1wOYgVr8zLQwwsfq+K/PfeOPitkKiPmUICeZXEXpTgOhkg53vynN+ZXwV4UcEKR64Z7LMK0mWqpCf3jzv8S9fu0/zV/cwo86LNbHPTRJtVxst25YUVL9X9U3lV7Q+KvRgephjuIG2gz/Ce63uVxVGiTMFETzeL0FM8hdSQUCcRKIFysDxhOh+oofPLkGQOQsET4atNYsqmEXOMnZjU07muqXTrsybz/PhTW2Ioi3AdCR/tfNnoOhBiON6hWyR66db8DKNfiyLmFvyEFsOLm5nNhucU4wvRslRyMfayn+D4nRc/I0I4ozifl0WXfqBbtAqFtUUV1cuWZfIDH9OJF5YfB2mbUs9FYo5CpopjNnGV8rlkzzGm15EWQhMTeq1qpxl+E2NsY0UZ3DoxLRzLEvoykpN9VatiYkrpX6jG9g2u1GZ6E/fDw5NwouUI/tLeaFhvHydMx7GVewKRNWuLC0hct92tKWtjV9tLCVzOoHGuDmWZVRLH6Zn5XJvCfhBZvu7RcM9S5UdJbdW5PYf8qYgTqteIoXYKQUofOGUCsbsBncLuiRT9I1pXMYolAcd06KfTdmhk6QHYCAN1JP6Rgz//r3osSc=
  file: 'src/tex/manual.pdf'
  on:
    repo: utwente-fmt/vercors
    tags: true
