name: build-test
# Only run the workflow when pushed to master, dev, or on pull requests.
on: 
  push:
    branches: 
      - master
      - dev
  pull-request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT dependencies modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-build-vercors-sbt-jdk11
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - run: sbt debian:packageBin
      - name: Archive VerCors .deb
        uses: actions/upload-artifact@v2
        with:
          name: vercors-debian-package
          retention-days: 1
          path: |
            target/*.deb
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [0, 1, 2, 3, 4]
    env:
      maxTestID: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: ls
      - run: "sudo dpkg -i *.deb"
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=${{ matrix.testID }}/${{ env.maxTestID }} vercors --test=examples --test-workers=1 --tool=silicon --exclude-suite=slow,medium,problem-fail,skip-travis --progress

