name: Slow tests
# Only run the workflow when a commit has been made to dev.

on:
  push:
    branches:
      - master
      - dev
      - issue-509-slow-tests

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - name: Cache SBT dependencies modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-build-vercors-sbt-jdk11
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Debug step 1
        run: |
          printf "${JAVA_HOME}\n"
          ls $JAVA_HOME
          ls $JAVA_HOME/bin
      - run: sbt debian:packageBin
      - name: Archive VerCors .deb
        uses: actions/upload-artifact@v2
        with:
          name: vercors-debian-package
          retention-days: 1
          path: |
            target/*.deb
      - name: Debug step 2
        run: |
          printf "${JAVA_HOME}\n"
          ls $JAVA_HOME
          ls $JAVA_HOME/bin

  slow_and_skip_travis_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [0, 1]
      fail-fast: false
    env:
      maxTestID: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: ls
      - run: "sudo dpkg -i *.deb"
      - run: mono --version
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=${{ matrix.testID }}/${{ env.maxTestID }} vercors --test=examples --test-workers=1 --tool carbon --tool silicon --include-suite=slow,medium,skip-travis --progress --actions-test-output

  problem_fail_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [0, 1]
      fail-fast: false
    env:
      maxTestID: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: ls
      - run: "sudo dpkg -i *.deb"
      - run: mono --version
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=${{ matrix.testID }}/${{ env.maxTestID }}  vercors --test=examples --test-workers=1 --tool carbon --tool silicon --include-suite=problem-fail --progress --actions-test-output || 1

  not_working_tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testID: [0, 1]
      fail-fast: false
    env:
      maxTestID: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre
      - name: Download VerCors binary
        uses: actions/download-artifact@v2
        with:
          name: vercors-debian-package
      - run: ls
      - run: "sudo dpkg -i *.deb"
      - run: mono --version
      - run: vercors --silicon examples/manual/fibonacci.pvl
      - run: SPLIT=${{ matrix.testID }}/${{ env.maxTestID }}  vercors --test=not_working_examples --test-workers=1 --tool carbon --tool silicon --progress --actions-test-output || 1
