name: 'Run ScalaTest'
# Only run the workflow when pushed to master, dev, or on pull requests.
on: 
  push:
    branches:
      - '**'
    tags-ignore: 
      - dev-prerelease
  pull_request:
    branches:
      - '**'
jobs:
  run-scalatest-vct:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: run scalatest
        run: sbt "testOnly vct.*" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport vct           # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-basic-and-veymont:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: run scalatest
        run: sbt "testOnly integration.BasicTests integration.BasicSlowTests integration.BasicVerySlowTests  integration.VeymontTests integration.ProblemFailTests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport basic and veymont            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-1:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: run scalatest
        run: sbt "testOnly integration.Generated1Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated1            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-2:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.Generated2Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated2            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-slow-1:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.GeneratedSlow1Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated slow 1            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-slow-2:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.GeneratedSlow2Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated slow 2            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-slow-3:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.GeneratedSlow3Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated slow 3            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-slow-4:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.GeneratedSlow4Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated slow 4            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

  run-scalatest-generated-slow-5:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Compile
        run: sbt compile
      - name: run scalatest
        run: sbt "testOnly integration.GeneratedSlow5Tests" || true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: TestReport Generated slow 5            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit

