name: 'Run ScalaTest'
# Only run the workflow when pushed to master, dev, or on pull requests.
on: 
  push:
    branches:
      - '**'
    tags-ignore: 
      - dev-prerelease
  pull_request:
    branches:
      - '**'
jobs:
  SkipDuplicate:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Check for duplicate workflow run
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # Never allow two runs of this workflow to exist
          concurrent_skipping: 'always'
          # Except, never skip a PR, scheduled, or manually dispatch run
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          # Skip if we can find a duplicate run with the same everything
          skip_after_successful_duplicate: 'true'
          # Do not run on changes only to these files
          paths_ignore: '["**/README.md", "**/LICENSE*"]'

  Compile:
    runs-on: ubuntu-latest
    needs: SkipDuplicate
    if: ${{ needs.SkipDuplicate.outputs.should_skip != 'true' }}

    steps:
    - name: Checkout VerCors
      uses: actions/checkout@v2
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache SBT and Viper
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/coursier
          ~/.ivy2/cache
          ~/.sbt
        key: sbt-viper-ubuntu-latest-${{ hashFiles('project/build.properties') }}-${{ hashFiles('build.sbt') }}
        restore-keys: |
          sbt-viper-ubuntu-latest-${{ hashFiles('project/build.properties') }}
    - name: Compile
      run: sbt pushRemoteCache
    - name: Upload precompiled repository
      uses: actions/upload-artifact@v3
      with:
        name: precompiled-repository
        path: tmp/vercors-build-cache

  ScalaTest:
    needs: "Compile"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        batch: ["-n MATRIX[0]", "-n MATRIX[1]", "-n MATRIX[2]", "-n MATRIX[3]", "-n MATRIX[4]", "-n MATRIX[5]", "-n MATRIX[6]", "-n MATRIX[7]", "-l MATRIX"]

    runs-on: ${{matrix.os}}
    environment: Default
    steps:
      - name: Checkout VerCors
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SBT and Viper
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/coursier
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-viper-${{ matrix.os }}-${{ hashFiles('project/build.properties') }}-${{ hashFiles('build.sbt') }}
          restore-keys: |
            sbt-viper-ubuntu-latest-${{ hashFiles('project/build.properties') }}
      - name: Download precompiled repository
        uses: actions/download-artifact@v3
        with:
          name: precompiled-repository
          path: tmp/vercors-build-cache
      - name: Pull cached compilation into sbt
        run: sbt pullRemoteCache compile

      # Windows: LLVM/Clang
      - name: Cache LLVM and Clang (windows)
        if: matrix.os == 'windows-latest'
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-10.0
      - name: Install LLVM and Clang (windows)
        if: matrix.os == 'windows-latest'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      # MacOS: LLVM/Clang
      - name: Install clang (mac)
        if: matrix.os == 'macos-latest'
        run: brew install llvm

      - name: Run scalatest for label ${{matrix.batch}}
        run: sbt "testOnly vct.* -- ${{matrix.batch}}"

      - name: Upload test reports
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ matrix.os }}-${{ matrix.batch }}
          path: tmp/vercors-build-cache

  GenerateTestReport:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: ScalaTest

    steps:
    - {name: Download Test Report ubuntu-0, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[0]", path: reports/ubuntu-0 }}
    - {name: Download Test Report ubuntu-1, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[1]", path: reports/ubuntu-1 }}
    - {name: Download Test Report ubuntu-2, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[2]", path: reports/ubuntu-2 }}
    - {name: Download Test Report ubuntu-3, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[3]", path: reports/ubuntu-3 }}
    - {name: Download Test Report ubuntu-4, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[4]", path: reports/ubuntu-4 }}
    - {name: Download Test Report ubuntu-5, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[5]", path: reports/ubuntu-5 }}
    - {name: Download Test Report ubuntu-6, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[6]", path: reports/ubuntu-6 }}
    - {name: Download Test Report ubuntu-7, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--n MATRIX[7]", path: reports/ubuntu-7 }}
    - {name: Download Test Report ubuntu-x, uses: actions/download-artifact@v3, with: {name: "test-report-ubuntu-latest--l MATRIX", path: reports/ubuntu-x }}

    - { name: Download Test Report windows-0, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[0]", path: reports/windows-0 } }
    - { name: Download Test Report windows-1, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[1]", path: reports/windows-1 } }
    - { name: Download Test Report windows-2, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[2]", path: reports/windows-2 } }
    - { name: Download Test Report windows-3, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[3]", path: reports/windows-3 } }
    - { name: Download Test Report windows-4, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[4]", path: reports/windows-4 } }
    - { name: Download Test Report windows-5, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[5]", path: reports/windows-5 } }
    - { name: Download Test Report windows-6, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[6]", path: reports/windows-6 } }
    - { name: Download Test Report windows-7, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--n MATRIX[7]", path: reports/windows-7 } }
    - { name: Download Test Report windows-x, uses: actions/download-artifact@v3, with: { name: "test-report-windows-latest--l MATRIX", path: reports/windows-x } }

    - { name: Download Test Report macos-0, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[0]", path: reports/macos-0 } }
    - { name: Download Test Report macos-1, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[1]", path: reports/macos-1 } }
    - { name: Download Test Report macos-2, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[2]", path: reports/macos-2 } }
    - { name: Download Test Report macos-3, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[3]", path: reports/macos-3 } }
    - { name: Download Test Report macos-4, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[4]", path: reports/macos-4 } }
    - { name: Download Test Report macos-5, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[5]", path: reports/macos-5 } }
    - { name: Download Test Report macos-6, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[6]", path: reports/macos-6 } }
    - { name: Download Test Report macos-7, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--n MATRIX[7]", path: reports/macos-7 } }
    - { name: Download Test Report macos-x, uses: actions/download-artifact@v3, with: { name: "test-report-macos-latest--l MATRIX", path: reports/macos-x } }

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: TestReport vct           # Name of the check run which will be created
        path: 'reports/**/TEST-*.xml'    # Path to test results
        reporter: java-junit