name: 'Run ScalaTest'
# Only run the workflow when pushed to master, dev, or on pull requests.
on: 
  push:
    branches:
      - '**'
    tags-ignore: 
      - dev-prerelease
  pull_request:
    branches:
      - '**'
jobs:
  run-scalatest:
    runs-on: ubuntu-latest
    environment: Default
    steps:
      # This should automatically cancel any previous workflows that are still
      # running when for example new commits are pushed.
      #- uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      # Currently sbt and fakeroot are installed by default
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: run scalatest
        run: sbt "testOnly integration.BasicTests" || true
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Scalatests report            # Name of the check run which will be created
          path: '**/target/test-reports/TEST-*.xml'    # Path to test results
          reporter: java-junit


